version: "3.8"
services:
    website:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        restart: on-failure:5
        networks:
            - murb_network

    websocket:
        build:
            context: ./websocket
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        environment:
            - NODE_ENV=production
        restart: on-failure:5
        networks:
            - murb_network

networks:
    murb_network:
        driver: bridge