name: Deploy to development

on:
    push:
        branches:
            - dev

jobs:
    DEPLOYING-WEBSITE:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'DEPLOY-DEV')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Get Instance Public IP
              id: get_ip
              run: |
                  INSTANCE_NAME="murb-dev-v1"
                  INSTANCE_IP=$(aws lightsail get-instance --instance-name $INSTANCE_NAME --query 'instance.publicIpAddress' --output text)
                  echo "INSTANCE_IP=${INSTANCE_IP}" >> $GITHUB_ENV

            - name: SSH into Lightsail Instance and Deploy
              run: |
                  # Copy the SSH key
                  mkdir -p ~/.ssh
                  echo "${{ secrets.DEFAULT_SSH_PRIVATE_KEY }}" > ~/.ssh/github
                  chmod 400 ~/.ssh/github

                  echo "INSTANCE_IP: $INSTANCE_IP"

                  # Deploying Now..!!
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/github ubuntu@${{ env.INSTANCE_IP }} 'bash -s' < ./deploy.sh
