name: Setup DNS

on:
    push:
        branches:
            - dev

jobs:
    SETUP:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'SETUP-DNS')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Get Instance Public IP
              id: get_ip
              run: |
                  INSTANCE_NAME="murb-dev-v1"
                  INSTANCE_IP=$(aws lightsail get-instance --instance-name $INSTANCE_NAME --query 'instance.publicIpAddress' --output text)
                  echo "INSTANCE_IP=${INSTANCE_IP}" >> $GITHUB_ENV

            - name: Setup DNS on Cloudflare
              run: |
                  RESPONSE=$(curl --request POST \
                  --url https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records \
                  --header "Content-Type: application/json" \
                  --header "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                  --data '{
                    "comment": "Domain verification record",
                    "name": "ws.dev.murb",
                    "proxied": false,
                    "ttl": 86400,
                    "content": "'"${{ env.INSTANCE_IP }}"'",
                    "type": "A"
                  }')

                  DNS_NAME=$(echo "$RESPONSE" | jq ".result.name")
                  echo "DNS Name:- $DNS_NAME"
